// Turns the real CLI captures in src/captures/ into a TS module the video can
// import. Re-run after re-capturing: bun run scripts/captures.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = join(import.meta.dir, "../src/captures");
const read = (f: string) => readFileSync(join(dir, f), "utf8").replace(/\n+$/, "");
const out = {
  install: read("install.txt").split("\n").filter((l) => l.trim()).join("\n"),
  search: read("search.ansi"),
  miraflores: read("miraflores.ansi").split("\n").slice(0, 13).join("\n"),
  urresti: read("urresti.ansi"),
  facts: read("facts.json.txt"),
  skill: read("skill.txt"),
};
writeFileSync(
  join(import.meta.dir, "../src/captures.generated.ts"),
  `// Generated by scripts/captures.ts from real \`votape\` output. Do not edit.\nexport const CAPTURES = ${JSON.stringify(out, null, 2)} as const;\n`,
);
console.log(Object.fromEntries(Object.entries(out).map(([k, v]) => [k, v.split("\n").length])));
